### PR TITLE
Support label feature

### PR DESCRIPTION
**Pull request by cosmo0920**
Fluentd 0.12 or later supports label feature.
Let's support this feature and keep backward compatibility!!

### CODE REVIEW

**Comment by okkez** [comment]
I think that need to update dependencies.

```ruby
gem.add_dependency "fluentd", "~> 0.10.30"
```

**Comment by cosmo0920** [comment]
Should I include updating fluentd dependency commit in this PR?

**Comment by okkez** [comment]
Yes, I think so.

**Comment by cosmo0920** [comment]
Hmm..., I don't think so.
I think that sending another PR to fix tests and bump up fluentd dependency is better.

**Comment by okkez** [comment]
OK. Let's create another PR!

**Comment by cosmo0920** [comment]
I've registered another PR #7.

**Pull request merged**
